1. Important Question:
  How do external factors such as holidays, temperature, fuel prices, and economic indicators (CPI and unemployment rate) influence weekly sales at Walmart?
  
  2. Importance of the Question:
  This question is essential for understanding the drivers behind Walmart's weekly sales performance. By analyzing the impact of external factors such as holidays, temperature, fuel prices, CPI, and unemployment rate on sales, we can gain insights into consumer behavior and market dynamics. Understanding these relationships can help Walmart optimize its operations, marketing strategies, and inventory management to maximize sales and profitability.

3. Data Collection:

Dependent Variable:
Weekly Sales: Total sales revenue generated by Walmart stores in a week.
Independent Variables:
Holiday_Flag: Indicator variable representing the presence (1) or absence (0) of a holiday.
Temperature: Air temperature in the region where Walmart stores are located.
Fuel_Price: Fuel cost in the region.
CPI (Consumer Price Index): Measure of the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services.
Unemployment: Unemployment rate in the region where Walmart stores are located.
4. Data Dictionary:

Dependent Variable:
Weekly Sales: Total sales revenue generated by Walmart stores in a week.

Independent Variables:
Holiday_Flag:
0: No holiday
1: Holiday week
Temperature:
Air temperature in Fahrenheit.
Fuel_Price:
Fuel cost in dollars per gallon.
CPI (Consumer Price Index):
Measure of the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services.
Unemployment:
Unemployment rate as a percentage of the labor force.