---
title: "MVA HW_1"
author: "Yasasvi"
date: "2024-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

1. Ask an important question you want answered 

Ans.

a. How do qualifying times (q1, q2, q3), driver performance (points), constructor performance (points), and circuit type (name) collectively affect the likelihood of a driver securing a podium position in a race?

Dependent Variable: Average lap time  
Independent Variables: Driver nationality, circuit location (latitude, longitude), circuit altitude, weather conditions

b. Examining the joint impact of driver performance (wins), circuit characteristics (location, altitude), weather conditions (latitude, longitude), and constructor nationality on race outcomes (position)?

Dependent Variable: Race outcomes (position)  
Independent Variables: Driver performance (wins), circuit characteristics (location, altitude), weather conditions (latitude, longitude), constructor nationality

c. Investigating the relationship between pit stop strategy (duration), race result (position), driver nationality, and circuit characteristics (location, altitude) across different seasons?

Dependent Variable: Race result (position)  
Independent Variables: Pit stop duration, driver nationality, circuit location, circuit altitude, season

2. Answer why this question(s) is/are important to you

Ans. Various factors such as circuit characteristics, weather conditions, pit stop strategy, qualifying positions etc., all impact/influence the final Grand prix result and can be crucial in helping teams optimize their race strategy, race dynamics, strategic decisions for achieving competitive race outcomes. 

3. Find and collect data (need one dependent variable and more than 3 dependent variables)

Ans. Kaggle F1 (1950 - 2023) dataset - https://www.kaggle.com/datasets/rohanrao/formula-1-world-championship-1950-2020

4. Describe your data (create a data dictionary)

Ans. 

circuit.csv:

circuitId: Unique identifier for the circuit.  
circuitRef: Reference code for the circuit.  
name: Name of the circuit.  
location: Location of the circuit.  
country: Country where the circuit is located.  
lat: Latitude coordinates of the circuit.  
lng: Longitude coordinates of the circuit.  
alt: Altitude of the circuit.  

constructor_results.csv:

constructorResultsId: Unique identifier for constructor results.  
raceId: Identifier for the race.  
constructorId: Unique identifier for the constructor.  
points: Points earned by the constructor.  
status: Status of the constructor results.  

constructor_standings.csv:

constructorStandingsId: Unique identifier for constructor standings.  
raceId: Identifier for the race.  
constructorId: Unique identifier for the constructor.  
points: Points earned by the constructor.  
position: Position of the constructor.  
positionText: Position text of the constructor.  
wins: Number of wins by the constructor.  

constructors.csv:

constructorId: Unique identifier for the constructor. 
constructorRef: Reference code for the constructor.  
name: Name of the constructor.  
nationality: Nationality of the constructor.  

driver_standings.csv:

driverStandingsId: Unique identifier for driver standings.  
raceId: Identifier for the race.  
driverId: Unique identifier for the driver.  
points: Points earned by the driver.  
position: Position of the driver.  
positionText: Position text of the driver.  
wins: Number of wins by the driver.  

drivers.csv:

driverId: Unique identifier for the driver.  
driverRef: Reference code for the driver.  
number: Driver's number.  
code: Code of the driver.  
forename: Forename of the driver.  
surname: Surname of the driver.  
dob: Date of birth of the driver.  
nationality: Nationality of the driver.  

lap_times.csv:

raceId: Identifier for the race.  
driverId: Unique identifier for the driver.  
lap: Lap number.  
position: Position of the driver.  
time: Lap time.  
milliseconds: Lap time in milliseconds.  

pit_stops.csv:

raceId: Identifier for the race.  
driverId: Unique identifier for the driver.  
stop: Pit stop number.  
lap: Lap number of the pit stop.  
time: Time of the pit stop.  
duration: Duration of the pit stop.  
milliseconds: Duration of the pit stop in milliseconds.  

qualifying.csv:

qualifyId: Unique identifier for qualifying.  
raceId: Identifier for the race.  
driverId: Unique identifier for the driver.  
constructorId: Unique identifier for the constructor.  
number: Qualifying number.  
position: Qualifying position.  
q1: Qualifying time for session 1.  
q2: Qualifying time for session 2.  
q3: Qualifying time for session 3.  

races.csv:

raceId: Unique identifier for the race.  
year: Year of the race.  
round: Round number.  
circuitId: Unique identifier for the circuit. 
name: Name of the race.  
date: Date of the race.  
time: Time of the race.  

results.csv:

resultId: Unique identifier for the result.  
raceId: Identifier for the race.  
driverId: Unique identifier for the driver.  
constructorId: Unique identifier for the constructor.  
number: Driver's number.  
grid: Starting grid position.  
position: Finishing position.  
positionText: Finishing position text.  
positionOrder: Finishing position order.  
points: Points earned.  

seasons.csv:

year: Year of the season.  

sprint_results.csv:

resultId: Unique identifier for the sprint result.  
raceId: Identifier for the race.  
driverId: Unique identifier for the driver.  
constructorId: Unique identifier for the constructor.  
number: Driver's number.  
grid: Starting grid position.  
position: Finishing position.  
positionText: Finishing position text.  
positionOrder: Finishing position order.  
points: Points earned.  

status.csv:

statusId: Unique identifier for the status.  
status: Status of the race.  